= ai-basketball-ws

This application is responsible for persisting uploaded videos through the use of Postgres and S3 as well as passing on details about the information a Pose Recognition Service in order to perform pose recognition against the video. It does this by receiving an initial request with details about the uploaded video where it persists this into a Postgres database. A unique identifier is then generated which we return to the client. The client then uses this as the Filename of the video in a multipart request to a second route. We stream this request to S3 with the filename (minus the extension) as the key. 

After the video is uploaded to S3, we then persist the storage URI of it into the database (we might not actually need to do this...) and then send this to the pose recognition service. Once we receive a successful response from the pose recognition service we can respond with 201 to the client! 

:toc:

== Getting Started

.HTTP API
[%header]
|===
|URI |HTTP Method |JSON Body |Required headers |Description
|/v1/example
|POST
|<body goes here>
|<headers go here>
|<description of API>
|===


== Development

This service relies on Minio and Postgres. It is not required for normal development, but to run in "Dev mode" or to run System Testing you will need to have Minio and Postgres running (see below on setup).

=== Run Minio Locally

```
docker run -p 9000:9000 minio/minio server /data
```

To view a Minio Dashboard, go to: http://127.0.0.1:9000/
. Username: minioadmin
. Password: minioadmin

=== Run Postgres Locally

```
docker run --rm -itd --name aibasketball -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=mydb -p 5432:5432 postgres
```

=== Local development

Install required packages: `npm install`

Run Unit and Integration tests:
```
npm test
```

Build and run locally:
```
# Start in development mode:
npm run start:dev
```

== Build & Deploy

To build: `npm run build`

To run: `npm start`

Test Docker build locally:
```
npm install && npm run build
docker build -t ai-basketball-ws .
```

== Running

```
npm start
```

== Conventions
=== Directory structure
 /
 |- config/          # Config file per environment. For running in containerised environment, set NODE_ENV.
 |- proto/           # Location for Protobuf files
 |- src/modules/     # Almost wrapper functions around key components of the service
 |- src/entity/      # TypeORM entities go here
 |- src/enums/
 |- src/interfaces/
 |- src/routes/      # HTTP Routes used by Express
 |- src/utils/       # Miscellaneous helper functions
 |- test/            # For integration and system tests.
 |- src/App.ts       # The application code, keep it clean and testable.
 |- src/server.ts    # Code to run application as a stand-alone service.

=== Filenames
* Classes - <PascalCase>.ts
* Interfaces - I<PascalCase>.ts (Do prefix with I)
* Unit Tests - <PascalCase>.unit.test.ts
* Integration Tests - <PascalCase>.int.test.ts, place in test/integration/
* System Tests - <PascalCase>.st.test.ts, place in test/st/
